import React from 'react';
import ComingSoon from './ComingSoon';
import Paraphraser from './Paraphraser';
import JsonFormatter from './JsonFormatter';
import LoremIpsumGenerator from './LoremIpsumGenerator';
import CaseConverter from './CaseConverter';
import WordCharacterCounter from './WordCharacterCounter';

// Dynamically import all tool components. For now, most will be ComingSoon.
const toolComponents: { [key: string]: React.ComponentType } = {
  'paraphraser': Paraphraser,
  'json-formatter': JsonFormatter,
  'lorem-ipsum-generator': LoremIpsumGenerator,
  'case-converter': CaseConverter,
  'text-cleaner': ComingSoon,
  'word-character-counter': WordCharacterCounter,
  'readability-score-checker': ComingSoon,
  'diff-merge-checker': ComingSoon,
  'base64-encoder-decoder': ComingSoon,
  'url-encoder-decoder': ComingSoon,
  'jwt-decoder': ComingSoon,
  'html-entity-encoder-decoder': ComingSoon,
  'uuid-guid-generator': ComingSoon,
  'qr-code-generator': ComingSoon,
  'password-generator': ComingSoon,
  'hash-generator': ComingSoon,
  'random-data-generator': ComingSoon,
  'favicon-generator': ComingSoon,
  'markdown-to-html': ComingSoon,
  'html-to-markdown': ComingSoon,
  'yaml-to-json-converter': ComingSoon,
  'json-to-yaml-converter': ComingSoon,
  'csv-to-json-converter': ComingSoon,
  'epoch-timestamp-converter': ComingSoon,
  'timezone-converter': ComingSoon,
  'iso-date-formatter': ComingSoon,
  'unit-converter': ComingSoon,
  'currency-converter': ComingSoon,
  'image-compressor': ComingSoon,
  'image-resizer-cropper': ComingSoon,
  'svg-optimizer': ComingSoon,
  'exif-metadata-viewer': ComingSoon,
  'pdf-to-images-converter': ComingSoon,
  'color-picker-palette': ComingSoon,
  'gradient-generator': ComingSoon,
  'box-shadow-generator': ComingSoon,
  'border-radius-generator': ComingSoon,
  'css-playground': ComingSoon,
  'regex-tester': ComingSoon,
  'url-shortener': ComingSoon,
  'responsive-tester': ComingSoon,
  'meta-tag-previewer': ComingSoon,
  'robots-sitemap-generator': ComingSoon,
  'utm-builder': ComingSoon,
  'pwa-icons-generator': ComingSoon,
  'http-status-code-lookup': ComingSoon,
  'cron-expression-builder': ComingSoon,
  'regex-cheat-sheet': ComingSoon,
  'mime-type-lookup': ComingSoon,
  'dns-whois-lookup': ComingSoon,
  'ip-geo-lookup': ComingSoon,
  'ping-visualizer': ComingSoon,
  'http-header-inspector': ComingSoon,
  'websocket-tester': ComingSoon,
  'unicode-inspector': ComingSoon,
  'emoji-picker': ComingSoon,
  'percentage-calculator': ComingSoon,
  'loan-calculator': ComingSoon,
  'pdf-merger-splitter': ComingSoon,
  'csv-cleaner': ComingSoon,
};

export default toolComponents;
